=== BackupTheBerlios/railz/railz/src/jfreerails/data/cargo_and_terrain.dtd
<!ELEMENT Cargo EMPTY>
<!ATTLIST Cargo
    Category (Mail | Passengers | Fast_Freight  | Slow_Freight  | Bulk_Freight  ) #REQUIRED
    id ID #REQUIRED
    unitWeight ( 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 ) #REQUIRED
  >

<!ELEMENT Cargo_Types (Cargo)*>

<!ELEMENT TrackPieceTemplate EMPTY>
<!--
  ++ trackTemplate is a 9 bit binary number which encodes a track template.
  ++ A 1 indicates the presence of track.
  ++ Bit 8(MSB)   7	6   5	4   3	2   1	0(LSB)
  ++     NW	    N	NE  W	N/A E	SW  S	SE
  -->
<!ATTLIST TrackPieceTemplate trackTemplate CDATA #REQUIRED >

<!ELEMENT Consumes EMPTY>
<!ATTLIST Consumes
    Prerequisite ( 1 | 2 | 4 | 8 | 16 )  #IMPLIED
    Cargo IDREF #REQUIRED
  >

<!ELEMENT Converts EMPTY>
<!ATTLIST Converts
    input IDREF #REQUIRED
    output IDREF #REQUIRED
  >

<!ELEMENT Produces EMPTY>
<!ATTLIST Produces
    Cargo IDREF #REQUIRED
    Rate CDATA #REQUIRED
  >

<!ELEMENT Terrain_Types (Tile)*>

<!ELEMENT Tile EMPTY>

<!ATTLIST Tile
    Category (River | Ocean | Hill | Country) #REQUIRED
    rgb CDATA #REQUIRED
    id ID #REQUIRED
    baseValue CDATA #REQUIRED
  >

<!ELEMENT Building_Types (Building_Type)*>
<!ELEMENT Building_Type (TrackPieceTemplate|Converts|Consumes|Produces)*>
<!ATTLIST Building_Type
	id ID #REQUIRED
	baseValue CDATA #REQUIRED
	maintenance CDATA #REQUIRED
	stationRadius CDATA #IMPLIED
	category (Urban | Resource | Industry | Station) #REQUIRED
>

<!ELEMENT Types (Cargo_Types, Terrain_Types, Building_Types)>

=== BackupTheBerlios/railz/railz/src/jfreerails/data/cargo_and_terrain.xml
<!DOCTYPE Types SYSTEM "cargo_and_terrain.dtd">
<Types>
   <Cargo_Types>
      <Cargo id="Mail" Category="Mail" unitWeight="1" />
      <Cargo id="Passengers" Category="Passengers" unitWeight="2" />
      <Cargo id="Food" Category="Fast_Freight" unitWeight="2" />
      <Cargo id="Livestock" Category="Fast_Freight" unitWeight="3" />
      <Cargo id="Mfg._Goods" Category="Fast_Freight" unitWeight="3" />
      <Cargo id="Grain" Category="Slow_Freight" unitWeight="5" />
      <Cargo id="Coffee" Category="Slow_Freight" unitWeight="5" />
      <Cargo id="Export_Goods" Category="Slow_Freight" unitWeight="5" />
      <Cargo id="Petroleum" Category="Bulk_Freight" unitWeight="8" />
      <Cargo id="Oil" Category="Bulk_Freight" unitWeight="8" />
      <Cargo id="Wood" Category="Bulk_Freight" unitWeight="8" />
      <Cargo id="Sugar" Category="Bulk_Freight" unitWeight="8" />
   </Cargo_Types>
   <Terrain_Types>
<!-- Don't include slums for now, LL
      <Tile id="slums" Category="Urban" rgb="0" right-of-way="0"/>
-->
      <Tile id="Clear" Category="Country" rgb="00b400" baseValue="2000"/>
      <Tile id="Farm" Category="Country" rgb="48fc48" baseValue="3000"/>
      <Tile id="Desert" Category="Country" rgb="b42400" baseValue="500"/>
      <Tile id="Ocean" Category="Ocean" rgb="0000b4" baseValue="0"/>
      <Tile id="River" Category="River" rgb="0048d8" baseValue="0"/>
      <Tile id="Terminal" Category="Special" rgb="1" baseValue="1000"/>
      <Tile id="Jungle" Category="Country" rgb="4890fc" baseValue="1500"/>
      <Tile id="Hills" Category="Hill" rgb="b4b4b4" baseValue="1500"/>
      <Tile id="Foothills" Category="Hill" rgb="90d8fc" baseValue="2000"/>
      <Tile id="Mountain" Category="Hill" rgb="ffffff" baseValue="1000"/>
   </Terrain_Types>
   <Building_Types>
      <Building_Type id="Refinery" category="Industry"
      baseValue="6000">
      <!-- rgb="7" -->
         <Converts input="Oil" output="Petroleum" />
      </Building_Type>
      <Building_Type id="City" baseValue="10000" category="Urban"
      maintenance="0">
      <!-- rgb="ef901e" -->
         <Produces Cargo="Mail" Rate="40" />
         <Produces Cargo="Passengers" Rate="80" />
         <Consumes Cargo="Mail" Prerequisite="2" />
	 <Consumes Cargo="Passengers" Prerequisite="2" />
         <Consumes Cargo="Mfg._Goods" Prerequisite="2" />
         <Consumes Cargo="Food" Prerequisite="2" />
      </Building_Type>
      <Building_Type id="Village" baseValue="3000" category="Urban"
      maintenance="0">
      <!-- rgb="d86c48" -->
         <Produces Cargo="Mail" Rate="10" />
         <Produces Cargo="Passengers" Rate="40" />
         <Consumes Cargo="Mfg._Goods" Prerequisite="4" />
         <Consumes Cargo="Mail" Prerequisite="4" />
         <Consumes Cargo="Passengers" Prerequisite="4" />
      </Building_Type>
      <Building_Type id="Factory" baseValue="6000"
      category="Industry" maintenance="0">
	<!--  rgb="0000b7" -->
         <Converts input="Coffee" output="Export_Goods" />
         <Converts input="Wood" output="Export_Goods" />
         <Converts input="Sugar" output="Export_Goods" />
         <Converts input="Petroleum" output="Export_Goods" />
      </Building_Type>
      <Building_Type id="Harbour" baseValue="5000"
      category="Industry" maintenance="0">
	<!-- Category="Ocean" rgb="1eead2" -->
         <Produces Cargo="Mail" Rate="40" />
         <Produces Cargo="Passengers" Rate="40" />
         <Produces Cargo="Mfg._Goods" Rate="160" />
         <Converts input="Grain" output="Food" />
         <Converts input="Export_Goods" output="Export_Goods" />
         <Consumes Cargo="Grain" />
         <Consumes Cargo="Coffee" />
         <Consumes Cargo="Wood" />
         <Consumes Cargo="Sugar" />
      </Building_Type>
      <Building_Type id="Stock-Yard" baseValue="4000"
      category="Industry" maintenance="0">
      <!-- rgb="3" -->
         <Converts input="Livestock" output="Food" />
      </Building_Type>
      <Building_Type id="Food_Proc._Plant" baseValue="5000" category="Industry"
      maintenance="0">
      <!-- rgb="5" -->
         <Converts input="Grain" output="Food"/>
      </Building_Type>
      <Building_Type id="Cattle_Ranch" baseValue="3000" category="Resource"
      maintenance="0">
      <!-- rgb="4" -->
         <Produces Cargo="Livestock" Rate="160" />
      </Building_Type>
      <Building_Type id="Grain_Elevator" baseValue="3000" category="Resource"
      maintenance="0">
      <!-- rgb="fcfc48" -->
         <Produces Cargo="Grain" Rate="160" />
      </Building_Type>
      <Building_Type id="Oil_Well" baseValue="3000" category="Resource"
      maintenance="0">
      <!-- rgb="ef901d" -->
         <Produces Cargo="Oil" Rate="160" />
      </Building_Type>
      <Building_Type id="Lumber_Mill" baseValue="3000" category="Resource"
      maintenance="0">
      <!-- rgb="ef901c" -->
         <Produces Cargo="Wood" Rate="160" />
      </Building_Type>
      <Building_Type id="Sugar_Plant." baseValue="3000" category="Resource"
      maintenance="0">
      <!-- rgb="ef901f" -->
         <Produces Cargo="Sugar" Rate="160" />
      </Building_Type>
      <Building_Type id="Landing" baseValue="3000" category="Industry"
      maintenance="0">
      <!-- Category="River" rgb="0048d9" -->
         <Consumes Cargo="Grain" />
         <Consumes Cargo="Coffee" />
         <Consumes Cargo="Export_Goods" />
         <Consumes Cargo="Wood" />
         <Consumes Cargo="Sugar" />
      </Building_Type>
      <Building_Type id="depot" stationRadius="1" baseValue="50000"
      maintenance="2000" category="Station">
      <!--  X="9" Y="10" doubleTrack="false" RGBvalue="000007" maxConsecutivePieces="0" -->
      </Building_Type>
      <Building_Type id="station" stationRadius="2"
      baseValue="100000" maintenance="2000" category="Station">
      <!-- X="9" Y="12"  doubleTrack="false" RGBvalue="000008"
      maxConsecuativePieces="0"-->
      </Building_Type>
      <Building_Type id="terminal" stationRadius="3"
      baseValue="200000" maintenance="2000" category="Station">
      <!--  X="9" Y="14"  doubleTrack="false" maxConsecuativePieces="0"
      RGBvalue="000009" -->
      </Building_Type>
   </Building_Types>
</Types>
